services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/deploy/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - './apps/auth/.env'
    depends_on:
      - mongo

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/deploy/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    env_file:
      - './apps/reservations/.env'
    depends_on:
      - mongo
      - auth
