services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/deploy/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '5000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/deploy/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - '5001:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
